Repository GeomScale/volesti, pull requests merged in 2020-06, with the labels that each got.

#84 Update/restructure Readme
  README.md
  doc/credits.md
  doc/publications.md
Labels: documentation

#36 Sdpa format
  R-proj/NAMESPACE
  R-proj/R/RcppExports.R
  R-proj/R/read_sdpa_file.R
  R-proj/R/zzz.R
  R-proj/inst/extdata/sdpa_n2m3.txt
  R-proj/man/Rcpp_Spectrahedron.Rd
  R-proj/man/Spectrahedron.Rd
  R-proj/man/loadSdpaFormatFile.Rd
  R-proj/man/readSdpaFormatFile.Rd
  R-proj/man/writeSdpaFormatFile.Rd
  R-proj/src/Makevars
  R-proj/src/Makevars.win
  R-proj/src/polytopes_modules.cpp
  R-proj/src/spectrahedron.cpp
  R-proj/src/spectrahedron_module.cpp
  cran_gen/Makevars
  cran_gen/Makevars.win
  examples/CMakeLists.txt
  examples/spectrahedra/CMakeLists.txt
  examples/spectrahedra/README.md
  examples/spectrahedra/data/sdp_n2m3.txt
  examples/spectrahedra/readWriteSdpaFile.cpp
  include/SDPAFormatManager.h
  include/convex_bodies/spectrahedra/LMI.h
  include/convex_bodies/spectrahedra/spectrahedron.h
  test/CMakeLists.txt
  test/test_sdpa_format.cpp
Labels: enhancement

#85 Activate tests in github actions (and clang sanitizer)
  .github/workflows/cmake-clang.yml
Labels: tests

#86 GitHub actions for R interface
  .github/workflows/R-CDM-check.yml
  R-proj/src/Makevars
  README.md
Labels: tests

#89 Fix deprecated ftime in lpsolve
  R-proj/DESCRIPTION
  R-proj/src/Rproj_externals/lp_solve/commonlib.c
  cran_gen/NEWS.md
  cran_gen/README.md
Labels: warning

#91 fix bug in bcdhr
  include/random_walks/boundary_cdhr_walk.hpp
Labels: bug
