Repository GeomScale/volesti, pull requests merged in 2020-03, with the labels that each got.

#63 Folder name changed from R-prog to R-proj
  README.md
Labels: documentation

#66 Improve sampling
  R-proj/NAMESPACE
  R-proj/R/RcppExports.R
  R-proj/R/gen_cross.R
  R-proj/R/gen_cube.R
  R-proj/R/gen_simplex.R
  R-proj/man/direct_sampling.Rd
  R-proj/man/gen_cross.Rd
  R-proj/man/gen_cube.Rd
  R-proj/man/gen_simplex.Rd
  R-proj/man/sample_points.Rd
  R-proj/src/direct_sampling.cpp
  R-proj/src/sample_points.cpp
  include/annealing/ball_annealing.h
  include/convex_bodies/ballintersectconvex.h
  include/convex_bodies/hpolytope.h
  include/convex_bodies/vpolyintersectvpoly.h
  include/convex_bodies/vpolytope.h
  include/convex_bodies/zpolytope.h
  include/samplers/sample_only.h
  include/samplers/samplers.h
  include/volume/cooling_balls.h
  test/vol.cpp
Labels: enhancement

#70 Update readme, added doc and tutorials
  README.md
  doc/cpp_interface.md
  doc/r_interface.md
Labels: documentation

#29 Eigen implementation
  R-proj/src/direct_sampling.cpp
  R-proj/src/sample_points.cpp
  include/annealing/gaussian_annealing.h
  include/annealing/hpoly_annealing.h
  include/annealing/ratio_estimation.h
  include/cartesian_geom/point.h
  include/convex_bodies/ball.h
  include/convex_bodies/ballintersectconvex.h
  include/convex_bodies/ellipsoids.h
  include/convex_bodies/hpolytope.h
  include/convex_bodies/vpolyintersectvpoly.h
  include/convex_bodies/vpolytope.h
  include/convex_bodies/zonoIntersecthpoly.h
  include/convex_bodies/zpolytope.h
  include/generators/h_polytopes_gen.h
  include/generators/known_polytope_generators.h
  include/lp_oracles/solve_lp.h
  include/lp_oracles/vpolyoracles.h
  include/lp_oracles/zpolyoracles.h
  include/rotating.h
  include/rounding.h
  include/samplers/gaussian_samplers.h
  include/samplers/samplers.h
  include/volume/cooling_balls.h
  include/volume/cooling_hpoly.h
  include/volume/exact_vols.h
  include/volume/volume.h
  test/CMakeLists.txt
Labels: optimization

#73 Improvements in R interface
  R-proj/R/RcppExports.R
  R-proj/R/zonotope_approximation.R
  R-proj/man/Rcpp_VpolytopeIntersection.Rd
  R-proj/man/VpolytopeIntersection.Rd
  R-proj/man/direct_sampling.Rd
  R-proj/man/sample_points.Rd
  R-proj/man/volume.Rd
  R-proj/man/zono_approx.Rd
  R-proj/man/zonotope_approximation.Rd
  R-proj/src/direct_sampling.cpp
  R-proj/src/polytopes_modules.cpp
  R-proj/src/sample_points.cpp
  R-proj/src/volume.cpp
  R-proj/src/zonotope_approximation.cpp
  R-proj/tests/testthat/test_Hvol.R
  R-proj/tests/testthat/test_Vvol.R
  R-proj/tests/testthat/test_Zvol.R
  R-proj/tests/testthat/test_rounding.R
  cran_gen/NEWS.md
  include/convex_bodies/hpolytope.h
  include/convex_bodies/vpolytope.h
  include/convex_bodies/zpolytope.h
Labels: optimization

#75 Use billiard walk in SOB algorithm
  R-proj/src/volume.cpp
  include/volume/volume.h
  test/vol.cpp
Labels: bug
