Repository GeomScale/volesti, pull requests merged in 2022-11, with the labels that each got.

#239 Constrained Riemannian Hamiltonian Monte Carlo Walk
  examples/crhmc_prepare/data/cube10.ine
  examples/crhmc_sampling/.gitignore
  examples/crhmc_sampling/CMakeLists.txt
  examples/crhmc_sampling/README.md
  examples/crhmc_sampling/crhmc_sampling.cpp
  examples/logconcave/README.md
  examples/python_utilities/plot_ode.py
  examples/python_utilities/plot_samples.py
  include/ode_solvers/implicit_midpoint.hpp
  include/ode_solvers/ode_solvers.hpp
  include/ode_solvers/oracle_functors.hpp
  include/preprocess/crhmc/crhmc_problem.h
  include/preprocess/crhmc/lewis_center.h
  include/preprocess/crhmc/opts.h
  include/preprocess/crhmc/two_sided_barrier.h
  include/preprocess/crhmc/weighted_two_sided_barrier.h
  include/random_walks/crhmc/additional_units/auto_tuner.hpp
  include/random_walks/crhmc/additional_units/dynamic_regularizer.hpp
  include/random_walks/crhmc/additional_units/dynamic_step_size.hpp
  include/random_walks/crhmc/additional_units/dynamic_weight.hpp
  include/random_walks/crhmc/crhmc_walk.hpp
  include/random_walks/crhmc/hamiltonian.hpp
  include/random_walks/random_walks.hpp
  test/CMakeLists.txt
  test/benchmarks_crhmc_sampling.cpp
  test/crhmc_sampling_test.cpp
  test/ode_solvers_test.cpp
  test/test_norm_hypercube.txt
Labels: enhancement, GSoC22

#233 Feature/sampling correlation matrices
  .gitignore
  examples/correlation_matrices/.Rhistory
  examples/correlation_matrices/CMakeLists.txt
  examples/correlation_matrices/README.md
  examples/correlation_matrices/plot.py
  examples/correlation_matrices/sampler.cpp
  include/cartesian_geom/point.h
  include/convex_bodies/correlation_matrices/corre_matrix.hpp
  include/convex_bodies/correlation_matrices/correlation_spectrahedron.hpp
  include/convex_bodies/correlation_matrices/correlation_spectrahedron_MT.hpp
  include/convex_bodies/spectrahedra/spectrahedron.h
  include/matrix_operations/EigenvaluesProblems.h
  include/random_walks/compute_diameter.hpp
  include/random_walks/random_walks.hpp
  include/random_walks/uniform_billiard_walk.hpp
  include/sampling/sample_correlation_matrices.hpp
  include/sampling/sphere.hpp
  test/CMakeLists.txt
  test/sampling_correlation_matrices_test.cpp
Labels: enhancement, GSoC22

#248 Add documentation actions and fix doc issues
  .github/workflows/docs.yml
  include/convex_bodies/correlation_matrices/correlation_spectrahedron.hpp
  include/convex_bodies/correlation_matrices/correlation_spectrahedron_MT.hpp
Labels: documentation, CI

#249 Fix doctest compilation error and update actions
  .github/workflows/cmake-clang.yml
  .github/workflows/cmake-gcc.yml
  test/doctest.h
Labels: bug, CI

#251 Add rng parameter for MC integration + fix dimension bug
  include/integration/simple_MC_integration.hpp
  test/simple_mc_integration.cpp
Labels: bug, enhancement

#252 Fix README badges
  README.md
Labels: CI

#253 Basic c++ documentation addition
  include/cartesian_geom/cartesian_kernel.h
  include/cartesian_geom/point.h
  include/convex_bodies/ball.h
  include/convex_bodies/ballintersectconvex.h
  include/convex_bodies/convex_body.h
  include/convex_bodies/correlation_matrices/corre_matrix.hpp
  include/convex_bodies/correlation_matrices/correlation_spectrahedron.hpp
  include/convex_bodies/correlation_matrices/correlation_spectrahedron_MT.hpp
  include/convex_bodies/ellipsoid.h
  include/convex_bodies/hpolytope.h
  include/convex_bodies/orderpolytope.h
  include/convex_bodies/spectrahedra/spectrahedron.h
  include/convex_bodies/vpolyintersectvpoly.h
  include/convex_bodies/vpolytope.h
  include/convex_bodies/zonoIntersecthpoly.h
  include/convex_bodies/zpolytope.h
  include/generators/convex_bodies_generator.h
  include/generators/h_polytopes_generator.h
  include/generators/known_polytope_generators.h
  include/generators/order_polytope_generator.h
  include/generators/sdp_generator.h
  include/generators/v_polytopes_generators.h
  include/generators/z_polytopes_generators.h
  include/lp_oracles/misc_lp.h
  include/matrix_operations/EigenvaluesProblems.h
  include/misc/poset.h
  include/nlp_oracles/nlp_hpolyoracles.hpp
  include/nlp_oracles/nlp_vpolyoracles.hpp
  include/optimization/simulated_annealing.hpp
  include/preprocess/crhmc/crhmc_input.h
  include/preprocess/crhmc/crhmc_problem.h
  include/preprocess/crhmc/opts.h
  include/preprocess/crhmc/two_sided_barrier.h
  include/preprocess/crhmc/weighted_two_sided_barrier.h
  include/random_walks/crhmc/additional_units/auto_tuner.hpp
  include/random_walks/crhmc/additional_units/dynamic_regularizer.hpp
  include/random_walks/crhmc/additional_units/dynamic_step_size.hpp
  include/random_walks/crhmc/additional_units/dynamic_weight.hpp
  include/random_walks/crhmc/hamiltonian.hpp
  include/random_walks/ellipsoid_walks/dikin_walker.h
  include/random_walks/ellipsoid_walks/john_walker.h
  include/random_walks/ellipsoid_walks/vaidya_walker.h
  include/root_finders/newton_raphson.hpp
  include/sampling/mmcs.hpp
  include/sampling/parallel_mmcs.hpp
Labels: documentation
